# Configurazione di base del server
server.port=8000

# Configurazione di Kafka
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.consumer.group-id=group_id
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Configurazione di Redis
spring.redis.host=redis
spring.redis.port=6379
