services:
  db:
    image: postgres
    volumes:
      - ../__data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build:
      context: .
    command: bash -c "python manage.py runserver 0.0.0.0:9000"
    container_name: portfolio
    ports:
      - "9000:9000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
      - marketer