services:
  portfolio-db:
    image: postgres
    container_name: portfolio-db
    volumes:
      - ../__data/portfolios/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  portfolio-web:
    build:
      context: .
    command: bash -c "python manage.py runserver 0.0.0.0:9000"
    container_name: portfolio
    ports:
      - "9000:9000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - portfolio-db
      - marketer